# config/database.yml

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # The following settings are standard for Rails 7.1+ to improve performance
  # and allow concurrent reads/writes.
  journal_mode: WAL
  synchronous: normal
  journal_size_limit: 67108864 # 64MB
  cache_size: 2000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: storage/production.sqlite3